### ISSUE TITLE
PlayerDeath

### ISSUE THREAD

**Issue by GielinorR-S** [lare96/asteria-3.0#10]
when players die either PvP or PvM they DC and get a roll back.

**Comment by lare96** [comment]
Need more info, any errors print in the console?

**Comment by GielinorR-S** [comment]
ive fixed this problem but i have another quite urgent one, after ive switched a item during PvP it takes about 5 seconds too attack even if ive waited 2 seconds before switching.

**Comment by GielinorR-S** [comment]
also if a player dc's it doesnt save there account
it rolls back too the last saved

**Comment by lare96** [comment]
How exactly did you fix the problem?

**Comment by GielinorR-S** [comment]
There was a few item = null things missing etc...
EDIT :
those other 2 bugs are pretty urgent ! let me know when there fixed up please much respect :)

**Comment by lare96** [comment]
When I asked how you fixed the problem I was looking for a specific answer... show me the exact lines so I can fix it on the git.

**Comment by lare96** [comment]
Just got a chance to test this out, dumb mistake on my part. It'll be fixed just now.
