### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by EdwinHoksberg** [lare96/asteria-3.0#12]
Hi,

I am getting a error when I'm trying to build the project:

```
Error:(52, 5) Groovyc: The return type of com.asteria.game.item.Item[] harvestItems() in plugin.skills.fishing.Fishing is incompatible with [Lcom.asteria.game.item.Item; harvestItems() in com.asteria.game.character.player.skill.action.HarvestingSkillAction
. At [52:5]
```

I don't know if my IDE is causing the error, or your project, can you take a look at it?
I am using IntelliJ 14.1.3 on Ubuntu 14.04.

**Comment by lare96** [comment]
When did you download Asteria? Are you using the most up-to-date version? (If you downloaded within  the last 6 hours you have the most up-to-date version).

**Comment by EdwinHoksberg** [comment]
Yea I downloaded the master 1 hour ago.

**Comment by lare96** [comment]
Odd, yeah I'm pretty sure it's your IDE. No one else seems to have this issue.
