### ISSUE TITLE
ItemOnItem scripts

### ISSUE THREAD

**Issue by fuzzout** [lare96/asteria-3.0#14]
It seems the ItemOnItem is lacking something;
but doubting my own coding ability, I thought I'd bring it here...

I tried running a switch (checking for context.itemUsed):
There was no effect, at all (not even debug on console)

I tried this:
    if (context.itemOn > 0) {
        player.encoder.sendMessage("Glorious.")
        }
That created a lot of exceptions...

Perhaps I did something wrong...? Would appreciate a tip. Thank you for the source! It is truly amazing.

**Comment by lare96** [comment]
Hi, when you say it created a lot of exceptions I need to see the specific exceptions it created.

**Comment by fuzzout** [comment]
Ohhh haaa, I maybe should've read it; the initial error was as follows:
Cannot compare an item (995) amount 1 with integer = 0

Okay... so the validation can't use items; my bad :)

I knew it was my fault! :D

so for future use:
context.ItemOn.getId() will need to be used in order to compare.

Functional block:
        if (context.itemOn.getId() > 0) {
        player.encoder.sendMessage("Glorious.")
        }

**Comment by lare96** [comment]
So you got everything working?

**Comment by fuzzout** [comment]
Aye sir! sorry about the trouble... Hey is there a place where I could leave some documentation regarding certain findings? (I imagine this might be useful for someone who wants to use Asteria).

I've now got a nifty block that does item on item.
