### ISSUE TITLE
Player doesn't face the victim during combat from the first start.

### ISSUE THREAD

**Issue by ghost** [lare96/asteria-3.0#16]
![screen shot 2015-06-18 at 1 57 48 am](https://cloud.githubusercontent.com/assets/2343694/8225027/86b5a9c0-155d-11e5-9cfb-b828541f5c99.png)

**Comment by ghost** [comment]
![screen shot 2015-06-18 at 1 57 28 am](https://cloud.githubusercontent.com/assets/2343694/8225032/9195841e-155d-11e5-9022-f7be7dceb561.png)

**Comment by lare96** [comment]
Just tried this, don't seem to be able to do it.

**Comment by ghost** [comment]
We use the entity-facing for combat right? Not the face-location.

**Comment by lare96** [comment]
yes, the entity index facing
