### ISSUE TITLE
Create grounditems null

### ISSUE THREAD

**Issue by supersoniko** [lare96/asteria-3.0#17]
I found another small bug in main Asteria git;

When a regular player dies, it tries to calculate the ground items, but something is referencing to nothing.

http://i.gyazo.com/0a2366ee28d14da7e48cb39b3e561851.png

http://gyazo.com/0a2366ee28d14da7e48cb39b3e561851

**Comment by ghost** [comment]
Not sure if related. But ammunition drop is also unpickable.

**Comment by lare96** [comment]
![](http://i.imgur.com/QrUzXoJ.png)
Nothing seems to be wrong with items dropped on death, Artem as for your issue I'm working on a fix right now.

**Comment by ghost** [comment]
Thanks.

**Comment by lare96** [comment]
Fixed 3c4155423f87520cd280a5333f9d1a77ef37c32b

**Comment by lare96** [comment]
Oh, this happens when the player is killed by an NPC... this is why you gotta be specifc
