### ISSUE TITLE
NPC Walking Clipping

### ISSUE THREAD

**Issue by AshotN** [lare96/asteria-3.0#27]
Currently, NPC's can walk through walls and objects

**Comment by Promises** [comment]
Applies to players who disable class8

**Comment by AshotN** [comment]
I'm sorry I don't understand what you mean by that.

**Comment by Promises** [comment]
Client sided noclip

**Comment by AshotN** [comment]
The client doesn't dictate where NPC's walk, maybe you mean Player noclip'ing, which is a seperate problem.

**Comment by Promises** [comment]
Hanve my first comment :)

**Comment by AshotN** [comment]
I'm sorry I don't understand

**Comment by lare96** [comment]
This is well known... server sided pathfinding hasn't and probably won't be added.

**Comment by AshotN** [comment]
Why won't it be added?

What are the possible remedies to this?

**Comment by lare96** [comment]
It's a lot of work, especially for a proper implementation. The vast majority of servers have half-assed slow implementations and I don't want to intentionally include code like that in this.

AFAIK https://github.com/apollo-rsps/apollo is the only server that has a good implementation of it, if you want to rip it from there feel free to.

The possible remedies are a proper pathfinding implementation lol

**Comment by ghost** [comment]
I have a proper implementation of the a traversal map system. The only thing I'm missing would be pathfinders. A\* player pathfinder is done. Have no clue for others(npc walking/following). If you need anything regarding this, add me on skype: artembatutin.
