### ISSUE TITLE
Packet 87 sending incorrect data to client.

### ISSUE THREAD

**Issue by ghost** [lare96/asteria-3.0#3]
Current implementation is sending a short with a ByteOrder of Big and an int with a ByteOrder of big. Short should have a ByteOrder of LITTLE and the Int should have a ByteOrder of MIDDLE.
Here's the correct implementation: 

```
    public PacketEncoder sendIntState(int id, int state) {
        DataBuffer out = DataBuffer.create();
        out.newPacket(87, player.getSession().getEncryptor());
        out.putShort(id, ByteOrder.LITTLE);
        out.putInt(state, ByteOrder.MIDDLE);
        player.getSession().send(out);
        return this;
    }
```

**Comment by lare96** [comment]
included in this 756478b19cf3ee4489e83c2822cdfcaf127ca210 commit
