### ISSUE TITLE
Position instance movement.

### ISSUE THREAD

**Issue by ghost** [lare96/asteria-3.0#30]
https://github.com/lare96/asteria-3.0/blob/master/src/com/asteria/game/location/Position.java#L179

Maybe it should be "z" instead of 0 for the height? You already have the position instance which you only move the X and Y values. The Z must be the same. May be problematic when you'll move something at a higher height.

By all means, I'd suggest make the Position class immutable.

**Comment by ArtemBatutin** [comment]
By all means, I'd suggest make the Position class immutable.

**Comment by lare96** [comment]
I agree with both your concerns, although I probably won't be taking the time out to make the class immutable. I highly recommend whoever is using this to do so though.

**Comment by lare96** [comment]
The '0' means that the Z coordinate won't be modified
