### ISSUE TITLE
Cap the NPC dynamic drop table to a maximum of 3 randomly selected drops

### ISSUE THREAD

**Issue by lare96** [lare96/asteria-3.0#7]
Currently, if you have 20 drops in the dynamic table, in theory, all 20 of them are potential drops. I'm going to cap it at a maximum of 3.

**Comment by Lmctruck30** [comment]
Also check to make sure things that are rare only drop once

**Comment by ghost** [comment]
I'd suggsest to not cap it down to 3. I would make it more and more harder(in chance) to drop another rare.

Let's say you have one rare dropped. The chance was 5%

Well the next rare chance is 10%. As you already received a rare, your chances decrease.

Just a small idea.

**Comment by atomicint** [comment]
@Xion543 That isn't how RS drop tables work.

Each mob has their own unique drop table that it usually drops items from, rare drops shouldn't go in this table. Unlike the unique drop table (hence why it is unique to each individual mob), many mobs share a 'rare' drop table.

So establishing a hierarchy for this shouldn't be too difficult:
```
- DropTable
    - UniqueDropTable
    - RareDropTable
```

The chances of hitting the rare drop table when slaying any mob is either 1/16 (for easier mobs) or 1/64 (for bosses)

Contained within the rare drop table are obviously the rare item drops, however many entries within this table are empty, i.e 'null' so the odds of rolling an empty index within the table are much higher than rolling a rare item.

This is also means that we have been doing the ROW wrong for quite some time; the ROW does not affect how OFTEN the rare drop table is accessed, so the 1/16 or 1/64 chances of hitting the drop table are the same but when the rare drop table is accessed, the ROW 'removes' the empty (null) indexes from the table, thus making it more likely that you will receive a rare item.

Now defining the hierarchy for this kind of system is actually pretty abstract, so it would be easy to implement.

Let's create a dependency graph; 

- DropTable
    * mob identifier - this can probably be moved, the redundancy with this is not a good idea, but for explanation sake, I'll leave it here.
    * list items

        - StandardDropTable - the chance of receiving any item from the standard drop table is determined by a chance, each item has a chance, which is typically based upon their relative value
        - RareDropTable - The rare drop table has two sub tables to select from as well as the regular rare drops, the rare drop table has a total weight of 128.
            * DropTable - gem table has a weight of 20/128, which contains mostly gems but also half keys, rune javelins, chaos talismans, and nature talismans.
            * DropTable - 'mega-rare' table has a weight of 15/128, and contains mostly empty (null) drops, but also rune spear, dragon spear, and shield left half. This is the table that the ROW removes 'empty' (null) drops from.
            * DropTable - it makes sense to have a method inside here which selects the table to choose from, instead of taking it out of this class. Could be 'this' or 'mega-rare' or 'gem' depending on the rolls.

- MobDrop
    * mob identifier
    * weight, 16 or 64 (remember above^?)
    * 100% drop, always drop (bones/ashes)
    * StandardDropTable - the normal drops
    * StandardDropTable - potential second drop; this can drop whether or not a main or rare drop occured, the only 'second' drops in RS are HARD clue scrolls, and drasonic visage
    * RareDropTable - the rare drops
    * QuestDrop - not going into detail about this, since we typically don't write quests

Note: I am currently unsure of how secondary drops are determined as they are considered 'rare' but can be dropped alongside a main drop, but not another drop from the rare drop table.

I will ask some JMods at a later date on how it actually works (my guess would be the same as the mega-rare/gem table)

Selecting the table to choose from, in a gist:

```java
List<Item> populate(Player player, Mob mob) {
    MobDrop drop = mob.getDrops();
    if(drop == null) return; // notify mob has no drops

    List<Item> drops = new ArrayList<>();
    if(random(drop.getWeight()) == 1) {
        RareDropTable rares = drop.getRareDropTable();
        DropTable table = rares.select();
        List<Item> potential = table.getItems();
        Collections.shuffle(potential, SECURE_RANDOM);
        Item item = potential.get(0);
        if(item != null) drops.add(item); // adds the first
    }

    if(drops.isEmpty()) { // if we were unable to select from or received an empty slot, try and get an item from the standard table
        DropTable table = drop.getStandardDrops();
        // iteration seems necessary here
        for(Item item : table.getItems()) {
            if(item == null) break; // empty slot, don't continue.
            double chance = Math.random() * 100.0;
            if((chance -= item.getDropChance()) < 0) {
                drops.add(item);
                break;
            }
        }
    }

    return items;
}
```

Another note: This is all pseudo-code, I have not actually written a production version of this design as it is not yet complete in my eyes. Please criticize and help me solve some of these design issues ;-)

**Comment by ghost** [comment]
Thanks for the information. :+1:

**Comment by lare96** [comment]
Finished this today :)
